### ISSUE TITLE
/gitlab settings provides no feedback

### ISSUE THREAD

**Issue by DHaussermann** [manland/mattermost-plugin-gitlab#50]
`/gitlab settings [setting] [value]` provides no feedback in the form of an ephemeral post that anything has happened. 

There should be feedback that this change was saved.

**Comment by manland** [comment]
The only possible path which return nothing is a bad action. For example `/gitlab setting notification on` (setting instead of settings). Now you will have a message!

But thank you very much for this issue because I completely missed settings.notifications=off :sweat_smile: It does nothing in the plugin... I fix it with the fix for this issue!
