### ISSUE TITLE
Unable to upgrade/install latest 0.3.0

### ISSUE THREAD

**Issue by uhlhosting** [manland/mattermost-plugin-gitlab#62]
Encountered an error when extracting the plugin. Review your plugin file content and try again.

**Comment by jasonblais** [comment]
@uhlhosting Did you download the tar.gz file from https://github.com/manland/mattermost-plugin-gitlab/releases ? It worked for e

**Comment by hanzei** [comment]
@manland FYI: You have both a release `v0.3.0` and a tag `0.3.0`.

**Comment by manland** [comment]
Thanks to report the issue! I have deleted the bad `0.3.0`! I think @uhlhosting you have downloaded the tar.gz of source code instead of [the compiled artifact](https://github.com/manland/mattermost-plugin-gitlab/releases/download/v0.3.0/com.github.manland.mattermost-plugin-gitlab-0.3.0.tar.gz) in v0.3.0 ;)
